### PR TITLE
Fix dart analyze

### PR DESCRIPTION
**Pull request by manhduc-nguyen**

### CODE REVIEW

**Comment by manhduc-nguyen** [comment]
@mduccc can u fix this last one, I don't understand the logic here.

Screen Shot 2022-06-09 at 17 48 18

**Comment by mduccc** [comment]
> @mduccc can u fix this last one, I don't understand the logic here.
> 
> Screen Shot 2022-06-09 at 17 48 18

> 

`ds_refresh_cupertino_sliver.dart` is an edited version of `refresh_cupertino_sliver.dart` from flutter core.

So I think don't need to fix analyze for that file. Just ignore.
@manhduc-nguyen

**Comment by manhduc-nguyen** [comment]
> > @mduccc can u fix this last one, I don't understand the logic here.
> > Screen Shot 2022-06-09 at 17 48 18
> 
> > 
> 
> `ds_refresh_cupertino_sliver.dart` is an edited version of `refresh_cupertino_sliver.dart` from flutter core.
> 
> So I think don't need to fix analyze for that file. Just ignore. @manhduc-nguyen

**Comment by manhduc-nguyen** [comment]
@mduccc cool, I see

**Pull request closed without merging**
