### PR TITLE
Implement Name Account screen

### PR DESCRIPTION
**Pull request by mduccc**

### CODE REVIEW

**Comment by manhduc-nguyen** [comment]
@mduccc lets hide the `Advanced` button in app bar for now. the MVP version wont have that feature.

**Comment by mduccc** [comment]
> 

Yes. I had to hide that button

**Comment by mduccc** [comment]
> @mduccc lets hide the `Advanced` button in app bar for now. the MVP version wont have that feature.

Yes. I hid that button

**Review by manhduc-nguyen — APPROVED** [review]
LGTM

**Pull request merged**
